CREATE TABLE region_list(
	record_id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,	
   region_id VARCHAR(150),
   last_known_location VARCHAR(150) NOT NULL 
);
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Burdorff');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Burdorff');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vattweir');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vattweir');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vattweir');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Razwan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Hirundum');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Anchor');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Maribor');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Dorndal');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Gors Velen');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Dorian');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Maribor');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Maribor');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Hirundum');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vizima');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Gors Velen');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Caelf');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Anchor');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vattweir');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Hirundum');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vizima');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Gors Velen');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Dorndal');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Dorndal');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Gors Velen');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Hirundum');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Dorndal');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vizima');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Caelf');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Vattweir');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Temeria','Caelf');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Daevon');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Daevon');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Fort Leyda');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Kaer Morhen');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Fort Leyda');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Daevon');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Daevon');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ard Carraigh');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ard Carraigh');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Fort Leyda');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Vengerberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Fort Leyda');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Vengerberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Fort Leyda');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Daevon');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Vengerberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Ard');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ard Carraigh');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Fort Leyda');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ard Carraigh');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Kaedwen','Ban Glean');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Kalkar');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Asheberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Kalkar');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Kalkar');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Asheberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Asheberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Asheberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Asheberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Eysenlaan');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Asheberg');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Gulet');
INSERT INTO region_list(region_id,last_known_location) VALUES ( 'Aedirn','Hagge');
